spring:
  application:
     name: suggest-spotify-playlist-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    
error:
  path=/error

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8081   # HTTP (Tomcat) port


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic